apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: devops-challenge
type: Opaque
stringData:
  ENVIRONMENT: "PROD"
  HOST: "0.0.0.0"
  PORT: "8000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"